#!/bin/sh

echo "Start PHP CodeStyle Fixer pre commit hook";

git status --porcelain | grep -e '^[AM]\(.*\).php$' | cut -c 3- | while read line; do
        phpcs fix --diff --rules=@PSR2 "$line";
        git add "$line";
    done

echo "Done PHP CodeStyle Fixing";

echo "PHP Mess Detector with custom ruleset report:";
phpmd.phar src text messdetector-ruleset.xml
echo "Done report.";

